sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tCyAYXC5geNze36rtUk
    access-key-secret: 68teXrfx9yVuOG271PR40pdah35RoI
    bucket-name: le-repo
